name: dartfx
description: A simple lightly function expression runer for dart and javascript.
version: 1.0.4

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  logger: ^1.1.0
  intl: ^0.17.0
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
