name: dartfx
description: A simple lightly function calculator for dart and javascript.
version: 1.0.6
repository: https://github.com/youngchan1988/dartfx
issue_tracker: https://github.com/youngchan1988/dartfx/issues

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  logger: ^1.1.0
  intl: ^0.17.0
  analyzer: ^3.1.0
  convert: ^3.0.1
  crypto: ^3.0.1
  meta: ^1.7.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
